# Generated by Django 5.2.15 on 2026-06-10 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='description',
        ),
    ]
