# Generated by Django 5.2.15 on 2026-06-10 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('inspections', '0002_remove_checklistitem_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=6, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='company.contractor')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to='company.employee')),
                ('responsible_engineer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tickets', to='company.employee')),
                ('source_result', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='ticket', to='inspections.inspectionitemresult')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='company.store')),
            ],
            options={
                'ordering': ('due_date', '-created_at'),
            },
        ),
    ]
