# Generated by Django 5.2.15 on 2026-06-28 14:08

from django.db import migrations, models

def migrate_ticket_statuses(apps, schema_editor):
    Ticket = apps.get_model("tickets", "Ticket")

    Ticket.objects.filter(status__in = ["new", "in_progress"]).update(status = "open")
    Ticket.objects.filter(status__in = ["done", "cancelled"]).update(status = "closed")

class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate_ticket_statuses,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed')], default='open', max_length=20),
        ),
    ]
