# Generated by Django 5.2.15 on 2026-06-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('cluster_director', 'Cluster Director'), ('store_director', 'Store Director'), ('chief_engineer', 'Chief Engineer'), ('engineer', 'Engineer')], max_length=30)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='company.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('cluster_director', models.OneToOneField(limit_choices_to={'position': 'cluster_director'}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_cluster', to='company.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_number', models.PositiveIntegerField(unique=True)),
                ('address', models.CharField(max_length=255)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='company.cluster')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='company.contractor')),
                ('responsible_engineer', models.ForeignKey(limit_choices_to={'position': 'engineer'}, on_delete=django.db.models.deletion.PROTECT, related_name='engineering_stores', to='company.employee')),
                ('store_director', models.OneToOneField(limit_choices_to={'position': 'store_director'}, on_delete=django.db.models.deletion.PROTECT, related_name='managed_store', to='company.employee')),
            ],
        ),
    ]
